install:
	docker-compose -f docker-compose.builder.yml run --rm install
corona-h:
	docker-compose -f docker-compose-corona-homolog.yml up -d
corona-p:
	docker-compose -f docker-compose-corona-production.yml up -d
